# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       swi-prolog

# >> macros
# << macros

Summary:    Prolog Interpreter
Version:    5.6.50
Release:    0
Group:      Development/Languages
License:    LGPLv2.1
URL:        http://www.swi-prolog.org/
Source0:    %{name}-%{version}.tar.gz
Source1:    %{name}-rpmlintrc
Source2:    update-index.sh
Source100:  swi-prolog.yaml
Patch0:     configure-in.patch
Patch1:     pkconfig.patch
Patch2:     0001-FIXED-Bug-478-Possible-read-past-end-of-static-array.patch
Patch3:     0002-FIXED-Bug-479-Writing-outside-allocated-array-in-PL_.patch
Patch4:     0003-FIXED-Bug-480-Possible-memory-issue-with-error-messa.patch
Provides:   pl

%description
ISO/Edinburgh-style Prolog compiler.  Compliant with Part 1 of the ISO standard
for Prolog.  Covers all traditional Edinburgh Prolog features and shares many
features with Quintus and SICStus Prolog, including a compatible module system.
Very fast compiler, garbage collection (also on atoms), fast and powerful C/C++
interface, autoloading, GNU-readline interface.
 
SWI-Prolog has been designed and implemented such that it can easily be
modified for experiments with logic programming and the relation
between logic programming and other programming paradigms (such as the
object oriented XPCE environment).  SWI-Prolog has a rich set of
built-in predicates and reasonable performance, which makes it possible
to develop substantial applications in it.  The current version offers
a module system, garbage collection and an interface to the C language.


%package runtime-lib
Summary:    SWI-Prolog runtime environment dynamic lib
Group:      System/Resource Policy
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description runtime-lib
SWI-Prolog runtime environment dynamic lib.

%package doc
Summary:    Documentation for SWI-Prolog
Group:      Documentation
Requires:   %{name} = %{version}-%{release}

%description doc
This package contains SWI-Prolog documentation (manual pages, README, etc.).

%package library-core
Summary:    Minimal library of SWI-Prolog predicates
Group:      System/Resource Policy
Requires(preun): /bin/rm
Requires(post): %{name} = %{version}
Obsoletes:  %{name}-lib-core

%description library-core
This package contains a minimal collection of prolog predicates, just enough
to load foreign libraries.


%package library
Summary:    Library of SWI-Prolog predicates
Group:      Development/Languages
Requires:   %{name}-library-core = %{version}
Requires(post): %{name} = %{version}
Requires(postun): %{name} = %{version}
Obsoletes:  %{name}-lib

%description library
This package contains a collection of commonly used prolog predicates. You
need this is you are running non-precompiled prolog code.


%package devel
Summary:    Headers files and libraries for SWI-Prolog C-interface
Group:      Development/Libraries
Requires:   %{name}-runtime-lib = %{version}
Provides:   pl-devel

%description devel
This package contains headers files, etc. necessary for developing software
that uses the C-interface to SWI-Prolog.


%prep
%setup -q -n %{name}-%{version}/swi-prolog

# configure-in.patch
%patch0 -p1
# pkconfig.patch
%patch1 -p1
# 0001-FIXED-Bug-478-Possible-read-past-end-of-static-array.patch
%patch2 -p1
# 0002-FIXED-Bug-479-Writing-outside-allocated-array-in-PL_.patch
%patch3 -p1
# 0003-FIXED-Bug-480-Possible-memory-issue-with-error-messa.patch
%patch4 -p1
# >> setup
# << setup

%build
# >> build pre
#update config.sub and config.guess
cp /usr/lib/rpm/meego/config.sub src/
cp /usr/lib/rpm/meego/config.guess src/
cp /usr/lib/rpm/meego/config.sub packages/jpl/
cp /usr/lib/rpm/meego/config.guess packages/jpl/
cp /usr/lib/rpm/meego/config.sub packages/xpce/
cp /usr/lib/rpm/meego/config.guess packages/xpce/
cp /usr/lib/rpm/meego/config.sub packages/xpce/src/
cp /usr/lib/rpm/meego/config.guess packages/xpce/src/
#regenerate configure (there is patch to configure.in and pkconfig.pc.in)
cd src
autoconf --force
cd -
# << build pre

%configure --disable-static \
    --with-world \
    --enable-shared \
    --without-clib \
    --disable-gmp \
    --disable-readline \
    --disable-curses \
    --without-chr \
    --without-clpqr \
    --without-cpp \
    --without-db \
    --without-mp \
    --without-nlp \
    --without-ssl \
    --without-odbc \
    --without-pldoc \
    --without-plunit \
    --without-zlib \
    --without-sgml \
    --without-semweb \
    --without-table \
    --without-http \
    --without-xpce \
    ARCH=%{_arch} \
    PL=swipl


# >> build post
make ARCH=%{_arch} PLARCH=%{_arch}
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
# Perform a minimal installation, then separate eveything extra into
# subpackages. This whole thing is a huge hack... yuck, I hate myself.

make DESTDIR=%{buildroot} ARCH=%{_arch} install-lite

# Relocate Manual to /usr/share/doc/.
mkdir -p %{buildroot}/%{_defaultdocdir}
mv %{buildroot}/usr/lib/swipl-%{version}/doc %{buildroot}/%{_defaultdocdir}/swipl-%{version}
mv %{buildroot}/%{_libdir}/swipl-%{version}/library/MANUAL %{buildroot}/%{_defaultdocdir}/swipl-%{version}/MANUAL

# Link library to standard library directory
chmod 755 %{buildroot}/%{_libdir}/swipl-%{version}/lib/%{_arch}/libpl.so.%{version}
ln -s swipl-%{version}/lib/%{_arch}/libpl.so.%{version} %{buildroot}/%{_libdir}/libpl.so.%{version}
# << install post

%post runtime-lib -p /sbin/ldconfig

%postun runtime-lib -p /sbin/ldconfig

%preun library-core
# >> preun library-core
if [ $1 -eq 0 ]; then
/bin/rm -f -- %{_libdir}/swipl-%{version}/library/INDEX.pl
fi
# << preun library-core

%post library-core
# >> post library-core
cd %{_libdir}/swipl-%{version}/library
%{_libdir}/swipl-%{version}/bin/%{_arch}/swipl --quiet -f none -F none -g "make_library_index('.')" -t halt
# << post library-core

%post library
# >> post library
cd %{_libdir}/swipl-%{version}/library
%{_libdir}/swipl-%{version}/bin/%{_arch}/swipl --quiet -f none -F none -g "make_library_index('.')" -t halt
# << post library

%postun library
# >> postun library
cd %{_libdir}/swipl-%{version}/library
%{_libdir}/swipl-%{version}/bin/%{_arch}/swipl --quiet -f none -F none -g "make_library_index('.')" -t halt
# << postun library

%files
%defattr(-,root,root,-)
# >> files
#%defattr(-,root,root,-)
%{_libdir}/swipl-%{version}/bin/%{_arch}/swipl
%{_libdir}/swipl-%{version}/bin/swipl
%{_bindir}/swipl
%{_libdir}/swipl-%{version}/boot*.prc
# << files

%files runtime-lib
%defattr(-,root,root,-)
# >> files runtime-lib
%{_libdir}/swipl-%{version}/swipl
%{_libdir}/libpl.so.%{version}
%{_libdir}/swipl-%{version}/lib/%{_arch}/libpl.so.%{version}
# << files runtime-lib

%files doc
%defattr(-,root,root,-)
# >> files doc
%doc %{_defaultdocdir}/swipl-%{version}/Manual/
%doc %{_defaultdocdir}/swipl-%{version}/MANUAL
%doc %{_mandir}/man1/*.1.gz
# << files doc

%files library-core
%defattr(-,root,root,-)
# >> files library-core
%{_libdir}/swipl-%{version}/library/shlib.pl
%{_libdir}/swipl-%{version}/library/error.pl
%{_libdir}/swipl-%{version}/library/lists.pl
%exclude %{_libdir}/swipl-%{version}/library/INDEX.pl
# << files library-core

%files library
%defattr(-,root,root,-)
# >> files library
%{_libdir}/swipl-%{version}/library/qpforeign.pl
%{_libdir}/swipl-%{version}/library/sort.pl
%{_libdir}/swipl-%{version}/library/oset.pl
%{_libdir}/swipl-%{version}/library/main.pl
%{_libdir}/swipl-%{version}/library/clp/simplex.pl
%{_libdir}/swipl-%{version}/library/clp/clp_distinct.pl
%{_libdir}/swipl-%{version}/library/clp/bounds.pl
%{_libdir}/swipl-%{version}/library/clp/clpfd.pl
%{_libdir}/swipl-%{version}/library/clp/clp_events.pl
%{_libdir}/swipl-%{version}/library/dialect/iso/iso_predicates.pl
%doc %{_libdir}/swipl-%{version}/library/dialect/yap/README.TXT
%{_libdir}/swipl-%{version}/library/dialect/yap.pl
%{_libdir}/swipl-%{version}/library/dialect.pl
%{_libdir}/swipl-%{version}/library/statistics.pl
%{_libdir}/swipl-%{version}/library/emacs_interface.pl
%{_libdir}/swipl-%{version}/library/base64.pl
%{_libdir}/swipl-%{version}/library/quintus.pl
%{_libdir}/swipl-%{version}/library/broadcast.pl
%{_libdir}/swipl-%{version}/library/debug.pl
%{_libdir}/swipl-%{version}/library/listing.pl
%{_libdir}/swipl-%{version}/library/pairs.pl
%{_libdir}/swipl-%{version}/library/shell.pl
%{_libdir}/swipl-%{version}/library/prolog_stack.pl
%{_libdir}/swipl-%{version}/library/settings.pl
%{_libdir}/swipl-%{version}/library/heaps.pl
%{_libdir}/swipl-%{version}/library/www_browser.pl
%{_libdir}/swipl-%{version}/library/files.pl
%{_libdir}/swipl-%{version}/library/nb_set.pl
%{_libdir}/swipl-%{version}/library/option.pl
%{_libdir}/swipl-%{version}/library/tty.pl
%{_libdir}/swipl-%{version}/library/help.pl
%{_libdir}/swipl-%{version}/library/when.pl
%{_libdir}/swipl-%{version}/library/occurs.pl
%{_libdir}/swipl-%{version}/library/prolog_xref.pl
%{_libdir}/swipl-%{version}/library/qsave.pl
%{_libdir}/swipl-%{version}/library/readutil.pl
%{_libdir}/swipl-%{version}/library/rbtrees.pl
%{_libdir}/swipl-%{version}/library/unicode/blocks.pl
%{_libdir}/swipl-%{version}/library/unicode/unicode_data.pl
%{_libdir}/swipl-%{version}/library/explain.pl
%{_libdir}/swipl-%{version}/library/bim.pl
%{_libdir}/swipl-%{version}/library/url.pl
%{_libdir}/swipl-%{version}/library/ctypes.pl
%{_libdir}/swipl-%{version}/library/backcomp.pl
%{_libdir}/swipl-%{version}/library/record.pl
%{_libdir}/swipl-%{version}/library/nb_rbtrees.pl
%{_libdir}/swipl-%{version}/library/check.pl
%{_libdir}/swipl-%{version}/library/helpidx.pl
%{_libdir}/swipl-%{version}/library/ordsets.pl
%{_libdir}/swipl-%{version}/library/threadutil.pl
%{_libdir}/swipl-%{version}/library/make.pl
%{_libdir}/swipl-%{version}/library/utf8.pl
%{_libdir}/swipl-%{version}/library/gensym.pl
%{_libdir}/swipl-%{version}/library/operators.pl
%{_libdir}/swipl-%{version}/library/am_match.pl
%{_libdir}/swipl-%{version}/library/thread.pl
%{_libdir}/swipl-%{version}/library/apply_macros.pl
%{_libdir}/swipl-%{version}/library/checklast.pl
%{_libdir}/swipl-%{version}/library/apply.pl
%{_libdir}/swipl-%{version}/library/assoc.pl
%{_libdir}/swipl-%{version}/library/date.pl
%{_libdir}/swipl-%{version}/library/readln.pl
%{_libdir}/swipl-%{version}/library/aggregate.pl
%{_libdir}/swipl-%{version}/library/dif.pl
%{_libdir}/swipl-%{version}/library/ugraphs.pl
%{_libdir}/swipl-%{version}/library/prolog_clause.pl
%{_libdir}/swipl-%{version}/library/system.pl
%{_libdir}/swipl-%{version}/library/checkselect.pl
%{_libdir}/swipl-%{version}/library/edinburgh.pl
%{_libdir}/swipl-%{version}/library/prolog_source.pl
%{_libdir}/swipl-%{version}/library/edit.pl
%{_libdir}/swipl-%{version}/boot/parms.pl
%{_libdir}/swipl-%{version}/boot/syspred.pl
%{_libdir}/swipl-%{version}/boot/history.pl
%{_libdir}/swipl-%{version}/boot/bags.pl
%{_libdir}/swipl-%{version}/boot/messages.pl
%{_libdir}/swipl-%{version}/boot/toplevel.pl
%{_libdir}/swipl-%{version}/boot/qlf.pl
%{_libdir}/swipl-%{version}/boot/writef.pl
%{_libdir}/swipl-%{version}/boot/license.pl
%{_libdir}/swipl-%{version}/boot/topvars.pl
%{_libdir}/swipl-%{version}/boot/rc.pl
%{_libdir}/swipl-%{version}/boot/dwim.pl
%{_libdir}/swipl-%{version}/boot/autoload.pl
%{_libdir}/swipl-%{version}/boot/apply.pl
%{_libdir}/swipl-%{version}/boot/attvar.pl
%{_libdir}/swipl-%{version}/boot/init.pl
%{_libdir}/swipl-%{version}/boot/load.pl
# << files library

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_libdir}/swipl-%{version}/include/
%{_libdir}/swipl-%{version}/dotfiles/
%{_libdir}/swipl-%{version}/demo/
%{_libdir}/swipl-%{version}/bin/%{_arch}/plld
%{_libdir}/swipl-%{version}/bin/%{_arch}/plrc
%{_bindir}/plld
%{_bindir}/plrc
%{_libdir}/pkgconfig/swi-prolog.pc
%{_libdir}/swipl-%{version}/lib/%{_arch}/libpl.so
%exclude %{_libdir}/swipl-%{version}/lib/%{_arch}/libpl.a
# << files devel
